[package]
name = "helight_baker"
version = "0.1.0"
edition = "2021"

[profile.release]
# lto = true
# codegen-units = 1
# opt-level = 3
# strip = true
# debug = false



[dependencies]
cfor = "1.1.0"
image = "0.25.5"
lightmap = "0.2.0"
nalgebra = "0.33.2"
nalgebra-glm = "0.19.0"
uvgen = "0.2.0"
